# Generated by Django 5.2.1 on 2025-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
